FROM node:alpine AS builder

WORKDIR /timezone-webapp/frontend

RUN apk add --no-cache python3 make g++ \
    && ln -sf python3 /usr/bin/python

COPY package*.json /timezone-webapp/frontend/

RUN npm install

COPY . /timezone-webapp/frontend/

RUN npm run build

FROM nginx:alpine

COPY --from=builder /timezone-webapp/frontend/dist /usr/share/nginx/html

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
EXPOSE 443

CMD [ "nginx", "-g", "daemon off;" ]