FROM node:alpine AS builder

WORKDIR /timezone-webapp/frontend

RUN apk add --no-cache python3 make g++ \
    && ln -sf python3 /usr/bin/python

COPY package*.json /timezone-webapp/frontend/

RUN npm install

COPY . /timezone-webapp/frontend/

CMD [ "npm", "run", "dev" ]