FROM python:3.12.3-slim

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONFAULTHANDLER=1 \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100

WORKDIR /timezone-webapp/backend

COPY requirements.txt /timezone-webapp/backend/

RUN pip install --no-cache-dir -r requirements.txt

COPY . /timezone-webapp/backend/

COPY entrypoint.sh /timezone-webapp/backend/entrypoint.sh

ENTRYPOINT [ "/timezone-webapp/backend/entrypoint.sh" ]

CMD [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]