# Generated by Django 5.1.7 on 2025-04-05 06:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registration Date and Time'),
        ),
    ]
