# Generated by Django 5.1.7 on 2025-04-01 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 1, 7, 48, 7, 607711, tzinfo=datetime.timezone.utc), verbose_name='Registration Date and Time'),
        ),
    ]
