# Generated by Django 5.1.7 on 2025-04-05 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_alter_user_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 5, 5, 43, 30, 524642, tzinfo=datetime.timezone.utc), verbose_name='Registration Date and Time'),
        ),
    ]
